// Generated by tool/logo/generate_gradient_logo.dart. Do not edit manually.

// 20x26 pixel grid representation of the mascot
// ' ' = transparent, 'D' = Dark Blue, 'M' = Medium Blue, 'L' = Light Blue
const List<String> mascotGrid = [
  '                    ',
  '     DDD     DDD    ',
  '    DDDDD   DDDDD   ',
  '   DDDMMDDDDDMMDDD  ',
  '  DDDMMDDDDDDDDMDDD ',
  '  DDMMDDMMMLMMMDMDD ',
  '  DDMDDMMMMLLMMMDD  ',
  '   DDDMMMMMMLMMMMD  ',
  '   DDMMMMDMMLMDMMD  ',
  '   DMMDMMDDMMLDDMD  ',
  '  DDMDMMMMMMLLLLLDD ',
  '  DMMDMMMMLLLLLDDLD ',
  '  DMDMMMLLLLLLLLLLD ',
  '  DDDMMMLLLDLLLLLDD ',
  '  DDMMMLLLLMDDDDDD  ',
  '   DMMMLLLLMMMMDD   ',
  '   DMMMLLLLLMLLMD   ',
  '   DDMMMLLLLLLLMD   ',
  '    DDMMMLLLLLMMD   ',
  '     DDDMMLLLLMDD   ',
  '       DDMLLLMDD    ',
  '        DDMLLDD     ',
  '         DDLDD      ',
  '          DDD       ',
  '                    ',
  '                    ',
];
