name: jaspr_repo
description: Shared utilities and tools for contributing to the Jaspr project.
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter_lints: ^5.0.0
  jaspr_lints: # ^0.4.0
    path: ../jaspr_lints
  lints: ^5.1.1
