name: jaspr_repo
description: Shared utilities and tools for contributing to the Jaspr project.
publish_to: none

environment:
  sdk: ^3.13.0-0

resolution: workspace

dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.1.0
