import 'package:jaspr/server.dart';

import 'aggregated_route.dart';
import 'page.dart';

/// A reference to a taxonomy index route generated by [TaxonomyAggregator].
///
/// Represents the index page for a taxonomy (e.g., `/tags`).
/// For individual term routes, see [TaxonomyTermRouteInfo].
class TaxonomyRouteInfo extends AggregatedRouteInfo {
  const TaxonomyRouteInfo({
    required this.taxonomy,
    required super.url,
    super.data = const {},
  });

  /// The taxonomy name, e.g. `'tags'`.
  final String taxonomy;
}

/// A reference to a taxonomy term route generated by [TaxonomyAggregator].
///
/// Represents a page for a specific term (e.g., `/tags/dart`).
///
/// ```dart
/// final tagRefs = context.taxonomyTermRefs('tags');
/// for (final ref in tagRefs) {
///   print('${ref.term}: ${ref.url}');
///   // Output: dart: /tags/dart, flutter: /tags/flutter, ...
/// }
/// ```
class TaxonomyTermRouteInfo extends TaxonomyRouteInfo {
  const TaxonomyTermRouteInfo({
    required super.taxonomy,
    required this.term,
    required super.url,
    super.data = const {},
  });

  /// The normalized term name, e.g. `'dart'`.
  final String term;
}

/// Context extensions to access taxonomy data
/// in a component's build method.
///
/// These extensions require eager loading to be enabled
/// and a [TaxonomyAggregator] to be configured in [ContentApp].
///
/// ```dart
/// // Get all tag term refs.
/// final tagRefs = context.taxonomyTermRefs('tags');
///
/// // Get a specific term ref.
/// final dartRef = context.taxonomyTermRef('tags', 'dart');
///
/// // Get blog posts tagged "dart".
/// final dartPosts = context.pagesForTerm('tags', 'dart');
///
/// // Build a tag cloud with counts.
/// final tagCloud = context.taxonomyTermRefsWithCount('tags');
/// for (final MapEntry(:key, :value) in tagCloud.entries) {
///   print('${key.term}: $value posts');
/// }
/// ```
extension TaxonomyContext on BuildContext {
  List<AggregatedRouteInfo> get _routeInfos => InheritedAggregatedContext.of(this)?.routeInfos ?? [];

  /// Returns all term refs for the given [taxonomy].
  ///
  /// Each returned ref corresponds to a term route
  /// created by a [TaxonomyAggregator].
  /// The taxonomy index ref is excluded.
  List<TaxonomyTermRouteInfo> taxonomyTermRefs(String taxonomy) {
    if (kIsWeb) {
      throw UnsupportedError(
        'context.taxonomyTermRefs() is not supported on the client and only allowed to be called on the server.\n'
        'Wrap the call with a !kIsWeb check or move it out of any client component.',
      );
    }

    return _routeInfos.whereType<TaxonomyTermRouteInfo>().where((r) => r.taxonomy == taxonomy).toList();
  }

  /// Returns the term ref for the given [taxonomy] and [term],
  /// or `null` if no such ref exists.
  ///
  /// The [term] is normalized before matching,
  /// so both `'Dart'` and `'dart'` will find the same ref.
  TaxonomyTermRouteInfo? taxonomyTermRef(String taxonomy, String term) {
    if (kIsWeb) {
      throw UnsupportedError(
        'context.taxonomyTermRef() is not supported on the client and only allowed to be called on the server.\n'
        'Wrap the call with a !kIsWeb check or move it out of any client component.',
      );
    }

    final normalized = TaxonomyUtils.normalize(term);
    return _routeInfos.whereType<TaxonomyTermRouteInfo>()
        .where((r) => r.taxonomy == taxonomy && r.term == normalized)
        .firstOrNull;
  }

  /// Returns the index ref for the given [taxonomy], or null.
  TaxonomyRouteInfo? taxonomyIndexRef(String taxonomy) {
    if (kIsWeb) {
      throw UnsupportedError(
        'context.taxonomyIndexRef() is not supported on the client and only allowed to be called on the server.\n'
        'Wrap the call with a !kIsWeb check or move it out of any client component.',
      );
    }

    return _routeInfos.whereType<TaxonomyRouteInfo>()
        .where((r) => r.taxonomy == taxonomy && r is! TaxonomyTermRouteInfo)
        .firstOrNull;
  }

  /// Returns all content pages that have the given [term]
  /// in their frontmatter [taxonomy] field.
  ///
  /// Scans all pages for a list field matching [taxonomy]
  /// that contains [term] (normalized before matching).
  /// Taxonomy routes themselves are not included.
  ///
  /// For example, with frontmatter `tags: [Dart, Flutter]`,
  /// calling `pagesForTerm('tags', 'dart')` would match this page.
  List<Page> pagesForTerm(String taxonomy, String term) {
    if (kIsWeb) {
      throw UnsupportedError(
        'context.pagesForTerm() is not supported on the client and only allowed to be called on the server.\n'
        'Wrap the call with a !kIsWeb check or move it out of any client component.',
      );
    }

    final normalizedTerm = TaxonomyUtils.normalize(term);

    return pages.where((p) {
      final terms = p.data.page[taxonomy];
      if (terms is List) {
        return terms.any((t) => TaxonomyUtils.normalize(t.toString()) == normalizedTerm);
      }
      return false;
    }).toList();
  }

  /// Returns a map of term refs to their content page counts
  /// for the given [taxonomy].
  ///
  /// Each key is a [TaxonomyRouteInfo] created by a [TaxonomyAggregator],
  /// and each value is the number of content pages
  /// that have that term in their frontmatter.
  ///
  /// ```dart
  /// final tagCloud = context.taxonomyTermRefsWithCount('tags');
  /// for (final MapEntry(:key, :value) in tagCloud.entries) {
  ///   // key.term is the term name (e.g., 'dart')
  ///   // key.url is the term route URL (e.g., '/tags/dart')
  ///   // value is the count of content pages with that term
  /// }
  /// ```
  Map<TaxonomyTermRouteInfo, int> taxonomyTermRefsWithCount(String taxonomy) {
    if (kIsWeb) {
      throw UnsupportedError(
        'context.taxonomyTermRefsWithCount() is not supported on the client and only allowed to be called on the server.\n'
        'Wrap the call with a !kIsWeb check or move it out of any client component.',
      );
    }

    final refs = taxonomyTermRefs(taxonomy);

    final counts = <String, int>{};
    for (final p in pages) {
      final terms = p.data.page[taxonomy];
      if (terms is List) {
        for (final t in terms) {
          final normalized = TaxonomyUtils.normalize(t.toString());
          counts[normalized] = (counts[normalized] ?? 0) + 1;
        }
      }
    }

    return {for (final ref in refs) ref: counts[ref.term] ?? 0};
  }
}

/// Utility functions for taxonomy metadata.
///
/// Terms are normalized to lowercase with spaces replaced by dashes
/// (e.g., `'My Tag'` becomes `'my-tag'`).
abstract class TaxonomyUtils {
  /// Normalizes a taxonomy term value to lowercase with dashes.
  static String normalize(String value) {
    return value.toLowerCase().replaceAll(' ', '-');
  }
}
