include: package:jaspr_repo/package.yaml

plugins:
  jaspr_lints:
    path: packages/jaspr_lints
    diagnostics:
      sort_children_last: true
      prefer_html_components: true
      styles_ordering: true
