include: package:lints/recommended.yaml

analyzer:
  exclude:
    - tool/scaffold/**
    - tool/templates/**
  errors:
    deprecated_member_use: ignore # TODO: remove when upgrading to analyzer 8

linter:
  rules:
    sort_pub_dependencies: false # to group packages semantically
    prefer_relative_imports: true
    directives_ordering: true
    avoid_print: true
