include: package:jaspr_repo/package.yaml

analyzer:
  exclude:
    - tool/scaffold/**
    - tool/templates/**
    - tool/new_component_bricks/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
