include: package:jaspr_repo/package.yaml

analyzer:
  exclude:
    - tool/scaffold/**
    - tool/templates/**
  language:
    # TODO: Enable and fix remaining strict-casts diagnostics.
    # strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
linter:
  rules:
    # Disabled so that we can group dependencies semantically.
    sort_pub_dependencies: false
