import 'package:jaspr/jaspr.dart';
import 'package:website/constants/theme.dart';

final jasprTheme = {
  'root': Styles.text(color: textDark),
  'keyword': Styles.text(color: Color.hex('#5d48d5')),
  'string': Styles.text(color: Color.hex('#60a15f')),
  'attr': Styles.text(color: Color.hex('#c36077')),
  // 'comment': Styles.text(color: Color.hex('#6a737d')),
  // 'quote': Styles.text(color: Color.hex('#6a737d')),
  // 'selector-tag': Styles.text(color: Color.hex('#005cc5')),
  // 'subst': Styles.text(color: Color.hex('#24292e')),
  // 'number': Styles.text(color: Color.hex('#005cc5')),
  // 'literal': Styles.text(color: Color.hex('#005cc5')),
  // 'variable': Styles.text(color: Color.hex('#005cc5')),
  // 'template-variable': Styles.text(color: Color.hex('#005cc5')),
  // 'doctag': Styles.text(color: Color.hex('#032f62')),
  // 'title': Styles.text(color: Color.hex('#24292e')),
  // 'section': Styles.text(color: Color.hex('#d73a49')),
  // 'selector-id': Styles.text(color: Color.hex('#d73a49')),
  // 'type': Styles.text(color: Color.hex('#005cc5')),
  // 'tag': Styles.text(color: Color.hex('#24292e')),
  // 'name': Styles.text(color: Color.hex('#24292e')),
  // 'regexp': Styles.text(color: Color.hex('#032f62')),
  // 'link': Styles.text(color: Color.hex('#032f62')),
  // 'symbol': Styles.text(color: Color.hex('#d73a49')),
  // 'bullet': Styles.text(color: Color.hex('#d73a49')),
  // 'built_in': Styles.text(color: Color.hex('#005cc5')),
  // 'builtin-name': Styles.text(color: Color.hex('#005cc5')),
  // 'meta': Styles.text(color: Color.hex('#6a737d')),
  // 'deletion': Styles.background(color: Color.hex('#ffeef0')),
  // 'addition': Styles.background(color: Color.hex('#e6ffed')),
};
