import 'package:jaspr/jaspr.dart';
import 'package:website/constants/theme.dart';

final githubTheme = {
  'root': Styles.text(color: Color.hex('#333333')).background(color: Color.hex('#f8f8f8')),
  'comment': Styles.text(color: Color.hex('#999988'), fontStyle: FontStyle.italic),
  'quote': Styles.text(color: Color.hex('#999988'), fontStyle: FontStyle.italic),
  'keyword': Styles.text(color: Color.hex('#333333'), fontWeight: FontWeight.bold),
  'selector-tag': Styles.text(color: Color.hex('#333333'), fontWeight: FontWeight.bold),
  'subst': Styles.text(color: Color.hex('#333333'), fontWeight: FontWeight.normal),
  'number': Styles.text(color: Color.hex('#008080')),
  'literal': Styles.text(color: Color.hex('#008080')),
  'variable': Styles.text(color: Color.hex('#008080')),
  'template-variable': Styles.text(color: Color.hex('#008080')),
  'string': Styles.text(color: Color.hex('#dd1144')),
  'doctag': Styles.text(color: Color.hex('#dd1144')),
  'title': Styles.text(color: Color.hex('#000080'), fontWeight: FontWeight.bold),
  'section': Styles.text(color: Color.hex('#990000'), fontWeight: FontWeight.bold),
  'selector-id': Styles.text(color: Color.hex('#990000'), fontWeight: FontWeight.bold),
  'type': Styles.text(color: Color.hex('#445588'), fontWeight: FontWeight.bold),
  'tag': Styles.text(color: Color.hex('#000080'), fontWeight: FontWeight.normal),
  'name': Styles.text(color: Color.hex('#000080'), fontWeight: FontWeight.normal),
  'attribute': Styles.text(color: Color.hex('#000080'), fontWeight: FontWeight.normal),
  'regexp': Styles.text(color: Color.hex('#009926')),
  'link': Styles.text(color: Color.hex('#009926')),
  'symbol': Styles.text(color: Color.hex('#990073')),
  'bullet': Styles.text(color: Color.hex('#990073')),
  'built_in': Styles.text(color: Color.hex('#0086b3')),
  'builtin-name': Styles.text(color: Color.hex('#0086b3')),
  'meta': Styles.text(color: Color.hex('#999999'), fontWeight: FontWeight.bold),
  'deletion': Styles.background(color: Color.hex('#ffdddd')),
  'addition': Styles.background(color: Color.hex('#ddffdd')),
  'emphasis': Styles.text(fontStyle: FontStyle.italic),
  'strong': Styles.text(fontWeight: FontWeight.bold),
};

final lightBlueTheme = {
  'root': Styles.text(color: Color.hex('#000000')).background(color: Color.hex('#ffffff')),
  'comment': Styles.text(color: Color.hex('#6a737d')),
  'quote': Styles.text(color: Color.hex('#6a737d')),
  'keyword': Styles.text(color: Color.hex('#005cc5')),
  'selector-tag': Styles.text(color: Color.hex('#005cc5')),
  'subst': Styles.text(color: Color.hex('#24292e')),
  'number': Styles.text(color: Color.hex('#005cc5')),
  'literal': Styles.text(color: Color.hex('#005cc5')),
  'variable': Styles.text(color: Color.hex('#005cc5')),
  'template-variable': Styles.text(color: Color.hex('#005cc5')),
  'string': Styles.text(color: Color.hex('#032f62')),
  'doctag': Styles.text(color: Color.hex('#032f62')),
  'title': Styles.text(color: Color.hex('#24292e')),
  'section': Styles.text(color: Color.hex('#d73a49')),
  'selector-id': Styles.text(color: Color.hex('#d73a49')),
  'type': Styles.text(color: Color.hex('#005cc5')),
  'tag': Styles.text(color: Color.hex('#24292e')),
  'name': Styles.text(color: Color.hex('#24292e')),
  'attribute': Styles.text(color: Color.hex('#24292e')),
  'regexp': Styles.text(color: Color.hex('#032f62')),
  'link': Styles.text(color: Color.hex('#032f62')),
  'symbol': Styles.text(color: Color.hex('#d73a49')),
  'bullet': Styles.text(color: Color.hex('#d73a49')),
  'built_in': Styles.text(color: Color.hex('#005cc5')),
  'builtin-name': Styles.text(color: Color.hex('#005cc5')),
  'meta': Styles.text(color: Color.hex('#6a737d')),
  'deletion': Styles.background(color: Color.hex('#ffeef0')),
  'addition': Styles.background(color: Color.hex('#e6ffed')),
};

final jasprLightTheme = {
  'root': Styles.text(color: textDark),
  //
  'keyword': Styles.text(color: Color.hex('#5d48d5')),
  'string': Styles.text(color: Color.hex('#60a15f')),
  'attr': Styles.text(color: Color.hex('#c36077')),
  //
  /*'comment': Styles.text(color: Color.hex('#6a737d')),
  'quote': Styles.text(color: Color.hex('#6a737d')),
  'selector-tag': Styles.text(color: Color.hex('#005cc5')),
  'subst': Styles.text(color: Color.hex('#24292e')),
  'number': Styles.text(color: Color.hex('#005cc5')),
  'literal': Styles.text(color: Color.hex('#005cc5')),
  'variable': Styles.text(color: Color.hex('#005cc5')),
  'template-variable': Styles.text(color: Color.hex('#005cc5')),
  'doctag': Styles.text(color: Color.hex('#032f62')),
  'title': Styles.text(color: Color.hex('#24292e')),
  'section': Styles.text(color: Color.hex('#d73a49')),
  'selector-id': Styles.text(color: Color.hex('#d73a49')),
  'type': Styles.text(color: Color.hex('#005cc5')),
  'tag': Styles.text(color: Color.hex('#24292e')),
  'name': Styles.text(color: Color.hex('#24292e')),
  'regexp': Styles.text(color: Color.hex('#032f62')),
  'link': Styles.text(color: Color.hex('#032f62')),
  'symbol': Styles.text(color: Color.hex('#d73a49')),
  'bullet': Styles.text(color: Color.hex('#d73a49')),
  'built_in': Styles.text(color: Color.hex('#005cc5')),
  'builtin-name': Styles.text(color: Color.hex('#005cc5')),
  'meta': Styles.text(color: Color.hex('#6a737d')),
  'deletion': Styles.background(color: Color.hex('#ffeef0')),
  'addition': Styles.background(color: Color.hex('#e6ffed')),*/
};
