include: package:lints/recommended.yaml

analyzer:
# TODO: Reenable once migrated to analyzer v8.
#  plugins:
#    - custom_lint
  exclude:
    - lib/**.g.dart
    - templates/**

linter:
  rules:
    sort_pub_dependencies: true
    prefer_relative_imports: true
    directives_ordering: true

formatter:
  page_width: 120
  trailing_commas: preserve
