include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/**.g.dart
    - templates/**

linter:
  rules:
    sort_pub_dependencies: true
    prefer_relative_imports: true
    directives_ordering: true