version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dart_quotes_serverpod
      POSTGRES_PASSWORD: "CHANGE_ME"
    volumes:
      - dart_quotes_serverpod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "CHANGE_ME"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  dart_quotes_serverpod_data:
