# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

analyzer:
#   exclude:
#     - path/to/excluded/files/**

# Jaspr has a custom analyzer plugin 'jaspr_lints', which is enabled here.
#
# You can toggle Jaspr specific lint rules in the 'diagnostics' section below.
plugins:
  jaspr_lints:
    version: ^0.6.0
    diagnostics:
      prefer_html_components: true
      sort_children_last: true
      styles_ordering: true

# Uncomment the following section to enable or disable additional rules.

# linter:
#   rules:
#     camel_case_types: true

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

formatter:
  # Change this to your preferred line length.
  page_width: 120
  trailing_commas: preserve

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
