# Site Configuration
titleBase: DOCS
favicon: favicon.ico

# Social media links
social:
  - name: Github
    url: https://github.com/schultek
  - name: X/Twitter
    url: https://twitter.com/schultek_dev
  - name: Bluesky
    url: https://bsky.app/profile/schultek.dev