name: pub_social
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  jaspr: ^0.18.2
  jaspr_og: ^0.1.0
  pub_api_client: ^3.1.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
