import 'dart:io';
import 'dart:math' as math;
import 'package:image/image.dart' as img;
import 'package:path/path.dart' as path;

String _mapPixelChar(img.Pixel pixel) {
  final r = pixel.r.toInt();
  final g = pixel.g.toInt();
  final b = pixel.b.toInt();
  final a = pixel.a.toInt();

  if (a < 30) return ' ';

  // Map each original pixel color to its character ID
  final brandColors = [
    ('D', [47, 54, 153]),   // Dark Blue
    ('M', [77, 109, 243]),  // Medium Blue
    ('L', [153, 217, 234])  // Light Blue
  ];

  String closestChar = 'D';
  num minDist = double.infinity;
  for (final color in brandColors) {
    final char = color.$1;
    final orig = color.$2;
    final dist = math.pow(r - orig[0], 2) + math.pow(g - orig[1], 2) + math.pow(b - orig[2], 2);
    if (dist < minDist) {
      minDist = dist;
      closestChar = char;
    }
  }
  return closestChar;
}

List<String> _getMascotGrid(String imgPath) {
  final bytes = File(imgPath).readAsBytesSync();
  final image = img.decodePng(bytes);
  if (image == null) {
    throw Exception('Failed to decode PNG image at $imgPath');
  }

  final gridLines = <String>[];
  for (int y = 0; y < image.height; y++) {
    final rowChars = StringBuffer();
    for (int x = 0; x < image.width; x++) {
      final pixel = image.getPixel(x, y);
      rowChars.write(_mapPixelChar(pixel));
    }
    gridLines.add(rowChars.toString());
  }
  return gridLines;
}

void main() {
  // Locate script directory and assets
  final scriptUri = Platform.script;
  final scriptDir = path.dirname(scriptUri.toFilePath());
  final pixelArtPath = path.join(scriptDir, 'pixil_frame.png');

  print('Reading mascot grid from $pixelArtPath...');
  final mascotGrid = _getMascotGrid(pixelArtPath);

  // Format mascot grid lines as Dart string literals
  final mascotGridFormatted = mascotGrid.map((line) => "  '$line',").join('\n');

  final dartCode = """// Generated by tool/logo/generate_gradient_logo.dart. Do not edit manually.

// 20x26 pixel grid representation of the mascot
// ' ' = transparent, 'D' = Dark Blue, 'M' = Medium Blue, 'L' = Light Blue
const List<String> mascotGrid = [
$mascotGridFormatted
];
""";

  // Save to lib/src/helpers/print_logo_constants.dart
  final libDir = path.normalize(path.join(scriptDir, '..', '..', 'lib'));
  final dartOutputPath = path.join(libDir, 'src', 'helpers', 'print_logo_constants.dart');

  File(dartOutputPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(dartCode);

  print('Generated Dart constants file successfully: $dartOutputPath\\n');
}
