import 'package:jaspr/jaspr.dart';

final githubTheme = {
  'root': Styles.text(color: Color.hex('#333333')).background(color: Color.hex('#f8f8f8')),
  'comment': Styles.text(color: Color.hex('#999988'), fontStyle: FontStyle.italic),
  'quote': Styles.text(color: Color.hex('#999988'), fontStyle: FontStyle.italic),
  'keyword': Styles.text(color: Color.hex('#333333'), fontWeight: FontWeight.bold),
  'selector-tag': Styles.text(color: Color.hex('#333333'), fontWeight: FontWeight.bold),
  'subst': Styles.text(color: Color.hex('#333333'), fontWeight: FontWeight.normal),
  'number': Styles.text(color: Color.hex('#008080')),
  'literal': Styles.text(color: Color.hex('#008080')),
  'variable': Styles.text(color: Color.hex('#008080')),
  'template-variable': Styles.text(color: Color.hex('#008080')),
  'string': Styles.text(color: Color.hex('#dd1144')),
  'doctag': Styles.text(color: Color.hex('#dd1144')),
  'title': Styles.text(color: Color.hex('#990000'), fontWeight: FontWeight.bold),
  'section': Styles.text(color: Color.hex('#990000'), fontWeight: FontWeight.bold),
  'selector-id': Styles.text(color: Color.hex('#990000'), fontWeight: FontWeight.bold),
  'type': Styles.text(color: Color.hex('#445588'), fontWeight: FontWeight.bold),
  'tag': Styles.text(color: Color.hex('#000080'), fontWeight: FontWeight.normal),
  'name': Styles.text(color: Color.hex('#000080'), fontWeight: FontWeight.normal),
  'attribute': Styles.text(color: Color.hex('#000080'), fontWeight: FontWeight.normal),
  'regexp': Styles.text(color: Color.hex('#009926')),
  'link': Styles.text(color: Color.hex('#009926')),
  'symbol': Styles.text(color: Color.hex('#990073')),
  'bullet': Styles.text(color: Color.hex('#990073')),
  'built_in': Styles.text(color: Color.hex('#0086b3')),
  'builtin-name': Styles.text(color: Color.hex('#0086b3')),
  'meta': Styles.text(color: Color.hex('#999999'), fontWeight: FontWeight.bold),
  'deletion': Styles.background(color: Color.hex('#ffdddd')),
  'addition': Styles.background(color: Color.hex('#ddffdd')),
  'emphasis': Styles.text(fontStyle: FontStyle.italic),
  'strong': Styles.text(fontWeight: FontWeight.bold),
};