analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:jaspr_repo/package.yaml

linter:
  rules:
    avoid_types_as_parameter_names: false
