include: package:lints/recommended.yaml

linter:
  rules:
    sort_pub_dependencies: true
    prefer_relative_imports: true
    directives_ordering: true
    avoid_types_as_parameter_names: false

formatter:
  page_width: 120
  trailing_commas: preserve
