builders:
# =====================
# === Jaspr Options ===
# =====================
  jaspr_options:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildJasprOptions" ]
    build_extensions:
      "lib/$lib$":
        - "lib/jaspr_options.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - '.client.json'
      - '.styles.json'
    runs_before:
      - jaspr_web_compilers:entrypoint_bootstrap
# ========================
# === Client Component ===
# ========================
  client_module:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildClientModule" ]
    build_extensions:
      "lib/{{file}}.dart":
        - "lib/{{file}}.client.json"
        - "web/{{file}}.client.dart"
    auto_apply: dependents
    build_to: cache
  client_registry:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildClientRegistry" ]
    build_extensions:
      "lib/$lib$":
        - "web/main.clients.dart"
    required_inputs:
      - '.client.json'
    auto_apply: dependents
    build_to: cache
    runs_before:
      - jaspr_web_compilers:entrypoint_bootstrap
# ========================
# === Styles ===
# ========================
  styles_module:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildStylesModule" ]
    build_extensions:
      "lib/{{file}}.dart":
        - "lib/{{file}}.styles.json"
    auto_apply: dependents
    build_to: cache
# ========================
# === Platform Imports ===
# ========================
  imports:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "findPlatformImports" ]
    build_extensions:
      ".dart":
        - ".imports.json"
    auto_apply: dependents
    build_to: cache
  import_parts:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "writePlatformImports" ]
    build_extensions:
      ".imports.json":
        - ".imports.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - '.imports.json'
    runs_before:
      - jaspr_web_compilers:entrypoint_bootstrap
  stub:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildPlatformStubs" ]
    build_extensions:
      "lib/$lib$":
        - "lib/generated/imports/_web.dart"
        - "lib/generated/imports/_vm.dart"
        - "lib/generated/imports/_stubs.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - .imports.json
    runs_before:
      - jaspr_web_compilers:entrypoint_bootstrap
