builders:
# =====================
# === Options ===
# =====================
  server_options:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildServerOptions" ]
    build_extensions:
      "lib/{{file}}.server.dart":
        - "lib/{{file}}.server.options.dart"
    auto_apply: root_package
    build_to: source
    required_inputs:
      - 'clients.bundle.json'
      - 'styles.bundle.json'
    runs_before:
      - build_web_compilers:entrypoint
  client_options:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildClientOptions" ]
    build_extensions:
      "lib/{{file}}.client.dart":
        - "lib/{{file}}.client.options.dart"
    auto_apply: root_package
    build_to: source
    required_inputs:
      - 'clients.bundle.json'
    runs_before:
      - build_web_compilers:entrypoint
# ========================
# === Client Component ===
# ========================
  client_module:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildClientModule" ]
    build_extensions:
      "lib/{{file}}.dart":
        - "lib/{{file}}.client.module.json"
    auto_apply: all_packages
    build_to: cache
    required_inputs:
      - 'codec.bundle.json'
  clients_bundle:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildClientsBundle" ]
    build_extensions:
      "lib/$lib$":
        - "lib/clients.bundle.json"
    auto_apply: all_packages
    build_to: cache
    required_inputs:
      - '.client.module.json'
  client_entrypoint:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildClientEntrypoint" ]
    build_extensions:
      "lib/{{file}}.client.dart":
        - "web/{{file}}.client.dart"
    required_inputs:
      - 'clients.bundle.json'
    auto_apply: root_package
    build_to: cache
    runs_before:
      - build_web_compilers:entrypoint
# ========================
# === Styles ===
# ========================
  styles_module:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildStylesModule" ]
    build_extensions:
      ".dart":
        - ".styles.json"
    auto_apply: all_packages
    build_to: cache
  styles_bundle:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildStylesBundle" ]
    build_extensions:
      "lib/$lib$":
        - "lib/styles.bundle.json"
    auto_apply: all_packages
    build_to: cache
    required_inputs:
      - '.styles.json'
# ========================
# === Sync Mixins ===
# ========================
  sync_mixins_module:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildSyncMixins" ]
    build_extensions:
      ".dart":
        - ".sync.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - 'codec.bundle.json'
    runs_before:
      - build_web_compilers:entrypoint
# ========================
# === Codec ===
# ========================
  codec_module:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildCodecModule" ]
    build_extensions:
      ".dart":
        - ".codec.json"
    auto_apply: all_packages
    build_to: cache
  codec_bundle:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildCodecBundle" ]
    build_extensions:
      "lib/$lib$":
        - "lib/codec.bundle.json"
    auto_apply: all_packages
    build_to: cache
    required_inputs:
      - '.codec.json'
# ========================
# === Platform Imports ===
# ========================
  imports_module:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildImportsModule" ]
    build_extensions:
      ".dart":
        - ".imports.json"
    auto_apply: dependents
    build_to: cache
  import_output:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildImportsOutput" ]
    build_extensions:
      ".imports.json":
        - ".imports.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - '.imports.json'
    runs_before:
      - build_web_compilers:entrypoint
  stub:
    import: "package:jaspr_builder/builder.dart"
    builder_factories: [ "buildPlatformStubs" ]
    build_extensions:
      "lib/$lib$":
        - "lib/generated/imports/_web.dart"
        - "lib/generated/imports/_vm.dart"
        - "lib/generated/imports/_stubs.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - '.imports.json'
    runs_before:
      - build_web_compilers:entrypoint
