import '../../client/sources/bundle.dart';

final clientOptionsOtherSources = {
  ...clientBundleOutputs,
  'site|lib/other.client.dart': '''
    void main() {}
  ''',
  'site|pubspec.yaml': '''
    jaspr:
      mode: static
  ''',
};

final clientOptionsOtherOutputs = {
  'site|lib/other.client.options.dart':
      '// dart format off\n'
      '// ignore_for_file: type=lint\n'
      '\n'
      '// GENERATED FILE, DO NOT MODIFY\n'
      '// Generated with jaspr_builder\n'
      '\n'
      'import \'package:jaspr/client.dart\';\n'
      '\n'
      'import \'package:site/client_with_sc.dart\' deferred as _client_with_sc;\n'
      'import \'package:site/component_basic.dart\' deferred as _component_basic;\n'
      'import \'package:site/component_model_class.dart\'\n'
      '    deferred as _component_model_class;\n'
      'import \'package:site/component_model_extension.dart\'\n'
      '    deferred as _component_model_extension;\n'
      'import \'package:site/model_class.dart\' as _model_class;\n'
      'import \'package:site/model_extension.dart\' as _model_extension;\n'
      '\n'
      '/// Default [ClientOptions] for use with your Jaspr project.\n'
      '///\n'
      '/// Use this to initialize Jaspr **before** calling [runApp].\n'
      '///\n'
      '/// Example:\n'
      '/// ```dart\n'
      '/// import \'other.client.options.dart\';\n'
      '///\n'
      '/// void main() {\n'
      '///   Jaspr.initializeApp(\n'
      '///     options: defaultClientOptions,\n'
      '///   );\n'
      '///\n'
      '///   runApp(...);\n'
      '/// }\n'
      '/// ```\n'
      'ClientOptions get defaultClientOptions => ClientOptions(\n'
      '  clients: {\n'
      '    \'client_with_sc\': ClientLoader(\n'
      '      (p) => _client_with_sc.ClientWithSC(\n'
      '        child: p.mount(p.get<String>(\'child\')),\n'
      '        children: p\n'
      '            .get<List<Object?>>(\'children\')\n'
      '            .cast<String>()\n'
      '            .map((i) => p.mount(i))\n'
      '            .toList(),\n'
      '        childrenMap: p\n'
      '            .get<Map<String, Object?>>(\'childrenMap\')\n'
      '            .cast<String, String>()\n'
      '            .map((k, v) => MapEntry(k, p.mount(v))),\n'
      '      ),\n'
      '      loader: _client_with_sc.loadLibrary,\n'
      '    ),\n'
      '    \'component_basic\': ClientLoader(\n'
      '      (p) => _component_basic.Component(\n'
      '        p.get<String>(\'a\'),\n'
      '        b: p.get<int>(\'b\'),\n'
      '        c: p.get<double?>(\'c\'),\n'
      '        d: p.get<bool>(\'d\'),\n'
      '      ),\n'
      '      loader: _component_basic.loadLibrary,\n'
      '    ),\n'
      '    \'component_model_class\': ClientLoader(\n'
      '      (p) => _component_model_class.Component(\n'
      '        p.get<String>(\'a\'),\n'
      '        b: _model_class.ModelA.fromRaw(p.get<Map<String, dynamic>>(\'b\')),\n'
      '      ),\n'
      '      loader: _component_model_class.loadLibrary,\n'
      '    ),\n'
      '    \'component_model_extension\': ClientLoader(\n'
      '      (p) => _component_model_extension.Component(\n'
      '        p.get<String>(\'a\'),\n'
      '        b: _model_extension.ModelBCodec.fromRaw(\n'
      '          p.get<Map<String, dynamic>>(\'b\'),\n'
      '        ),\n'
      '      ),\n'
      '      loader: _component_model_extension.loadLibrary,\n'
      '    ),\n'
      '  },\n'
      ');\n'
      '',
};
