on:
  pull_request:
    branches:
      - main
      - next
    paths:
      - '.github/workflows/report.yml'
      - 'packages/**'

name: Report Pipeline

jobs:
  report:
    name: Version Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Bootstrap
        run: |
          flutter doctor
          dart pub global activate melos
          dart pub global activate -s git https://github.com/schultek/semantic_changelog
          melos bootstrap --no-private
          jaspr --disable-analytics

      - name: Bump Package Versions
        run: |
          version bump --dry-run --scope="packages/*" | tee output.txt
          echo "${{ github.event.number }}" > pr_number.txt

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-report
          path: |
            output.txt
            pr_number.txt
